module: JazzyKit
module_version: 1.1
author: PSPDFKit
author_url: http://pspdfkit.com/
objc: true
clean: true
framework_root: .
umbrella_header: MiscJazzyObjCFeatures/MiscJazzyObjCFeatures.h
sdk: iphonesimulator
separate_global_declarations: true
custom_categories:
- name: Ying
  children:
  - ObjCTopLevelClass
